safe: true
lsi: false
highlighter: 'pygments'
permalink: '/:categories/:year/:month/:title/'
exclude: [CNAME, LICENSE.md, README.md, bower.json, Gemfile, Gemfile.lock, Gruntfile.js, package.json, Vagrantfile, _less, manifests]
timezone: UTC
